# Generated by Django 6.0.2 on 2026-02-10 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='TeaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип чая')),
            ],
            options={
                'verbose_name': 'Тип чая',
                'verbose_name_plural': 'Типы чая',
            },
        ),
        migrations.CreateModel(
            name='Desert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('ingredients', models.TextField(blank=True, verbose_name='Состав')),
                ('mass_ingredients', models.TextField(blank=True, null=True, verbose_name='Состав/Вес (г)')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (г)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток на складе')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адрес (slug)')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Калорийность (ккал/100г)')),
                ('pieces', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество кусочков/порций')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Десерт',
                'verbose_name_plural': 'Десерты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('ingredients', models.TextField(blank=True, verbose_name='Состав')),
                ('mass_ingredients', models.TextField(blank=True, null=True, verbose_name='Состав/Вес (г)')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (г)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток на складе')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюда',
                'verbose_name_plural': 'Блюда',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('ingredients', models.TextField(blank=True, verbose_name='Состав')),
                ('mass_ingredients', models.TextField(blank=True, null=True, verbose_name='Состав/Вес (г)')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (г)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток на складе')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адрес (slug)')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бренд напитка')),
                ('volume', models.PositiveIntegerField(blank=True, null=True, verbose_name='Объём (мл)')),
                ('sugar_level', models.IntegerField(choices=[(0, 'Без сахара'), (25, '25%'), (50, '50%'), (100, '100%')], default=0, verbose_name='Уровень сахара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='shop.category', verbose_name='Категория')),
                ('tea_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drinks', to='shop.teatype', verbose_name='Вид чая')),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Напитки',
                'ordering': ['-created_at'],
            },
        ),
    ]
